### ISSUE TITLE
Remove metaLoop execution in parent repo

### ISSUE THREAD

**Issue by sramam** [mateodelnorte/meta-loop#16]
I'm trying to use meta to manage a bunch of child repos with meta - very convenient idea. Thank you.

Let's say each of these child repos has a npm run-script for linting: `npm run lint`.
`meta npm run lint` fails in the parent directory, because by [default](https://github.com/mateodelnorte/meta-loop/blob/master/index.js#L22), meta-loop seems to want to run the command in the parent repo. 

Strikes me that the meta repo should be managed independent of the child repos. 

Is there a chance this line can be removed?

**Comment by mateodelnorte** [comment]
You can run the command with `--ignore .` or `--ignore [parent dir name]`.

**Comment by mateodelnorte** [comment]
Sorry, I meant `--exclude .` or `--exclude [parent repo name]`.

**Comment by sramam** [comment]
hmm - the only way I was able to get this to work was to add a dummy sun-script in parent: package.json. Howeve, [this repo](https://github.com/sramam/meta-bug-16) reproduces the problem  I am encounering

**Comment by mateodelnorte** [comment]
this is not a bug. you only need to type the basename of the directory you're excluding. notice how this command does not print `pwd` for the parent meta repo: 
```
$ meta exec pwd --exclude meta

find-file-recursively-up:
/Users/matt/development/meta/plugins/find-file-recursively-up
find-file-recursively-up ✓

get-meta-file:
/Users/matt/development/meta/plugins/get-meta-file
get-meta-file ✓

loop:
/Users/matt/development/meta/plugins/loop
loop ✓

meta-exec:
/Users/matt/development/meta/plugins/meta-exec
meta-exec ✓

meta-gh:
/Users/matt/development/meta/plugins/meta-gh
meta-gh ✓

meta-git:
/Users/matt/development/meta/plugins/meta-git
meta-git ✓

meta-init:
/Users/matt/development/meta/plugins/meta-init
meta-init ✓

meta-loop:
/Users/matt/development/meta/plugins/meta-loop
meta-loop ✓

meta-npm:
/Users/matt/development/meta/plugins/meta-npm
meta-npm ✓

meta-project:
/Users/matt/development/meta/plugins/meta-project
meta-project ✓

meta-yarn:
/Users/matt/development/meta/plugins/meta-yarn
meta-yarn ✓

symlink-meta-dependencies:
/Users/matt/development/meta/plugins/symlink-meta-dependencies
symlink-meta-dependencies ✓
```

**Comment by mateodelnorte** [comment]
See more info here https://github.com/mateodelnorte/loop#loop

**Comment by sramam** [comment]
Interesting. I was able to make exec work too. It was the meta-npm that caused me trouble, So I tried exec'ing the npm command to the same effect:

`meta exec "npm run lint" --exclude /private/tmp/trial/meta-bug-16`
```
/private/tmp/trial/meta-bug-16:
npm ERR! missing script: lint

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sramam/.npm/_logs/2019-08-30T16_43_06_131Z-debug.log
/private/tmp/trial/meta-bug-16: command 'npm run lint' exited with error: Error: Command failed: npm run lint

repos/node-starter:

> @tufan/node-starter@1.0.0 lint /private/tmp/trial/meta-bug-16/repos/node-starter
> tslint -c tslint.json --project ./tsconfig.json --format stylish

no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
repos/node-starter ✓
```

`meta exec pwd --exclude /private/tmp/trial/meta-bug-16`
```
/private/tmp/trial/meta-bug-16:
/tmp/trial/meta-bug-16
/private/tmp/trial/meta-bug-16 ✓

repos/node-starter:
/private/tmp/trial/meta-bug-16/repos/node-starter
repos/node-starter ✓
 sramam  tmp  trial  meta-bug-16  master
```

Looking through the meta-npm module, it looked like the loop options were being stripped and it was upto the meta-loop to pick them up and process them again. I just took a cursory look - so very likely I missed something. 

Creating a dummy run-script in the mete repo works-around the issue - slightly unwieldy, but I'l live it. 

meta is a really cool take on multi/mono repos. Thanks for creating it. 

I'll leave it alone at this point unless you reopen the issue.
