### ISSUE TITLE
Add flag to exclude current directory

### ISSUE THREAD

**Issue by kevin-lindsay-1** [mateodelnorte/meta-loop#17]
## 🚀 Feature Proposal

Would be nice to say "run the following command in project directories, excluding this one".

## Motivation

I have projects that have different non-recursive slices of architecture, each that rely on meta projects, and there is not convenient way to say, for example, "recursively download metarepos and switch branches".

**Comment by mateodelnorte** [comment]
This is already built in. `meta-loop` inherits all flags that `loop` supports, so you can provide `--exclude .`

**Comment by kevin-lindsay-1** [comment]
Yeah, I originally attempted that, but it still appears to be running the command in the root folder.

Do you have an example of the correct syntax for that?

**Comment by mateodelnorte** [comment]
`--exclude-only .`
